/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ToolsImport } from './routes/tools'
import { Route as RolesImport } from './routes/roles'
import { Route as LuzImport } from './routes/luz'
import { Route as EducationalImport } from './routes/educational'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ToolsRoute = ToolsImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRoute,
} as any)

const RolesRoute = RolesImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRoute,
} as any)

const LuzRoute = LuzImport.update({
  id: '/luz',
  path: '/luz',
  getParentRoute: () => rootRoute,
} as any)

const EducationalRoute = EducationalImport.update({
  id: '/educational',
  path: '/educational',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/educational': {
      id: '/educational'
      path: '/educational'
      fullPath: '/educational'
      preLoaderRoute: typeof EducationalImport
      parentRoute: typeof rootRoute
    }
    '/luz': {
      id: '/luz'
      path: '/luz'
      fullPath: '/luz'
      preLoaderRoute: typeof LuzImport
      parentRoute: typeof rootRoute
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesImport
      parentRoute: typeof rootRoute
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/educational': typeof EducationalRoute
  '/luz': typeof LuzRoute
  '/roles': typeof RolesRoute
  '/tools': typeof ToolsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/educational': typeof EducationalRoute
  '/luz': typeof LuzRoute
  '/roles': typeof RolesRoute
  '/tools': typeof ToolsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/educational': typeof EducationalRoute
  '/luz': typeof LuzRoute
  '/roles': typeof RolesRoute
  '/tools': typeof ToolsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/educational' | '/luz' | '/roles' | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/educational' | '/luz' | '/roles' | '/tools'
  id: '__root__' | '/' | '/educational' | '/luz' | '/roles' | '/tools'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EducationalRoute: typeof EducationalRoute
  LuzRoute: typeof LuzRoute
  RolesRoute: typeof RolesRoute
  ToolsRoute: typeof ToolsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EducationalRoute: EducationalRoute,
  LuzRoute: LuzRoute,
  RolesRoute: RolesRoute,
  ToolsRoute: ToolsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/educational",
        "/luz",
        "/roles",
        "/tools"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/educational": {
      "filePath": "educational.tsx"
    },
    "/luz": {
      "filePath": "luz.tsx"
    },
    "/roles": {
      "filePath": "roles.tsx"
    },
    "/tools": {
      "filePath": "tools.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
